# Pymanopt tutorial 1

Minimize the following cost function 


function:

  $f = (x-x0)^\top \cdot A\cdot (x-x0)$


gradient:

  $\frac{\partial f}{\partial x} = 2\cdot A\cdot (x-x0)$



In [21]:
from pymanopt.manifolds import Product, Euclidean, Rotations
from pymanopt import Problem
from pymanopt.solvers import SteepestDescent

In [22]:
def cost(x):
    e = np.matrix(x)-np.matrix(x0)
    val = (e*np.matrix(A)*e.T).A1[0]
    return val

In [23]:
def egrad(x):
    e = np.matrix(x)-np.matrix(x0)
    return (np.matrix(A)*e.T).A1*2

In [24]:
# optimization in Euclidean space 
dim = 3

x_init = np.array([0,0,0])
x0 = np.array([1,2,3])
A = np.diag([0.1,0.1,0.1])

manifold = Euclidean(dim)
p = Problem(manifold=manifold, cost = cost, egrad = egrad)

solver = SteepestDescent()
Xopt = solver.solve(p, x = x_init)


Compiling cost function...
 iter		   cost val	    grad. norm
[[-1 -2 -3]]
    1	+1.4000000000000001e+00	7.48331477e-01
[[-0.73273876 -1.46547752 -2.19821627]]
    2	+7.5166852264521167e-01	5.48331477e-01
[[0.53126948 1.06253896 1.59380843]]
    3	+3.9514616088474019e-01	3.97565673e-01
[[-0.42741097 -0.85482194 -1.28223291]]
    4	+2.5575219027786950e-01	3.19845081e-01
[[0.03849716 0.07699432 0.11549148]]
    5	+2.0748437016433318e-03	2.88086355e-02
[[-0.03504646 -0.07009292 -0.10513938]]
    6	+1.7195562131798875e-03	2.62263700e-02
[[-0.02056416 -0.04112831 -0.06169247]]
    7	+5.9203829878176108e-04	1.53888050e-02
[[0.01859962 0.03719924 0.05579885]]
    8	+4.8432410425249727e-04	1.39186796e-02
[[0.01032647 0.02065294 0.03097941]]
    9	+1.4929033061708040e-04	7.72762138e-03
[[-0.00126074 -0.00252148 -0.00378221]]
   10	+2.2252435878567079e-06	9.43449752e-04
[[4.11597984e-05 8.23195968e-05 1.23479395e-04]]
   11	+2.3717806049736435e-09	3.08011727e-05
[[-3.41832490e-05 -6.83664981e-05 

In [25]:
print(Xopt)

[1.00000003 2.00000006 3.00000009]
